### PR TITLE
Added method call to redeem token.

### PR DESCRIPTION
**Pull request by ashishb**

### CODE REVIEW

**Comment by jorilallo** [comment]
Mind adding tests and error handling similar to other endpoints? small nitpick: `tokenId` should be `token_id`

**Comment by ashishb** [comment]
Hi @jorilallo 
I added tests and changed tokenId to token_id. Please take another look.

**Comment by ashishb** [comment]
Hi @jorilallo 
Friendly ping for review of this pull request.

**Comment by jorilallo** [comment]
Looks good, sorry for the delay!

**Comment by ashishb** [comment]
Thanks.


Ashish

**Pull request merged**
